[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E2E8F0"
textColor = "#1E3A8A"
linkColor = "#06B6D4"
# headingFont = "Roboto"

[browser]
gatherUsageStats = true

[client]
showErrorDetails = "none"