[theme]
primaryColor = "#E64980"
backgroundColor = "#FFFBFF" 
secondaryBackgroundColor = "#FCE7EC"
textColor = "#31394D"
linkColor = "#A23963"
# headingFont = "Roboto"

[browser]
gatherUsageStats = true

[client]
showErrorDetails = "none"